export const Colors = {
  primary: '#111F84',
  secondary: '#3044DD',
  white: '#FFFFFF',
  black: '#000',
  background: '#EDEFF9',
  border: '#EDEFF9',
  switchGray: '#E2E1E7',
  voteBarOui: '#D5DCFF',
  voteBarBlanc: '#BFC4DA',
  voteBarNon: '#FFD2D2',
  gradientStart: 'rgba(255, 255, 255, 0.1)',
  gradientEnd: '#FFFFFF',
  progressActive: '#3044DD',
  progressInactive: 'rgba(48, 68, 221, 0.25)',
};

export const Typography = {
  fontFamily: {
    medium: 'RethinkSans-Medium',
    mono: 'SpaceMono',
  },
  fontSize: {
    h1: 24,
    settingRow: 20,
    voteCount: 20,
    button: 20,
    body: 16,
    tabLabel: 16,
    small: 14,
  },
  fontWeight: {
    bold: '700' as const,
    semibold: '600' as const,
    medium: '500' as const,
  },
  lineHeight: {
    h1: 31,
    settingRow: 26,
    voteCount: 26,
    button: 26,
    body: 21,
    tabLabel: 16,
    small: 18,
  },
  letterSpacing: {
    h1: 0.48,
    settingRow: 0.4,
    voteCount: 0.2,
    button: 0.4,
    body: 0.16,
    tabLabel: -0.16,
    small: 0.14,
  },
};

export const Spacing = {
  screen: {
    horizontal: 32,
    top: 72,
    bottom: 8,
    gap: 8,
    sectionGap: 24,
  },
  video: {
    characterWidth: 71,
    characterHeight: 100,
    borderRadius: 8,
  },
  voteList: {
    paddingTop: 64,
    paddingHorizontal: 24,
    titlePaddingVertical: 8,
    itemPaddingVertical: 16,
    itemGap: 16,
  },
  voteCard: {
    padding: 32,
    gap: 24,
    badgeGap: 8,
    badgePaddingVertical: 4,
    badgePaddingHorizontal: 12,
    badgeRadius: 29,
    buttonPaddingVertical: 14,
    statsGap: 2,
    resultsGap: 8,
    resultsBarGap: 16,
    barPaddingVertical: 14,
  },
  settingRow: {
    paddingVertical: 24,
    paddingHorizontal: 32,
    gap: 24,
    valueGap: 8,
  },
  accordion: {
    padding: 32,
    gap: 24,
    titleGap: 16,
    contentGap: 8,
  },
  tabBar: {
    containerHeight: 120,
    height: 72,
    itemHeight: 64,
    borderRadius: 64,
    itemBorderRadius: 40,
    horizontalPadding: 24,
    bottomPaddingIOS: 24,
    bottomPaddingAndroid: 16,
    innerPadding: 4,
    maxWidth: 344,
  },
  modal: {
    borderRadius: 32,
    titlePadding: 32,
    titlePaddingHorizontal: 24,
    contentPadding: 40,
    contentPaddingHorizontal: 32,
    contentGap: 24,
    stepTitleGap: 16,
    footerPadding: 24,
    footerPaddingHorizontal: 32,
    footerGap: 39,
    progressBarHeight: 4,
    progressBarGap: 6,
    progressBarRadius: 4,
    arrowButtonSize: 48,
    arrowButtonRadius: 48,
    numberCircleSize: 32,
    cardImageWidth: 199,
    cardImageHeight: 167,
    phoneImageSize: 171,
  },
  icon: {
    size: 24,
    labelGap: 2,
  },
};

export const Shadows = {
  tabBar: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.1,
    shadowRadius: 24,
    elevation: 8,
  },
};
