/**
 * Expo config plugin: keep this app's data out of the phone's backups,
 * ON ANDROID ONLY.
 *
 * The first line of this header used to stop at "out of the phone's backups",
 * with no platform named, and the audit was right to call that false (4b-M15):
 * this plugin writes an Android manifest attribute and an Android resource
 * file, and NOTHING IN THIS REPOSITORY EXCLUDES ANYTHING FROM AN iOS BACKUP.
 * `NSURLIsExcludedFromBackupKey` and `isExcludedFromBackup` appear nowhere in
 * the tree; utils/app-config.test.ts checks that this paragraph stays here for
 * as long as that is true.
 *
 * What is in a device's iCloud or encrypted-iTunes backup today, measured:
 *   - AsyncStorage. On iOS it is a file under Documents/, which is backed up:
 *     the terms acceptance, the cached proposal list and signed index, the
 *     registration pending slot.
 *   - The Noir circuit files. utils/circuit-preload.ts:35 and :189 write them
 *     under `FileSystem.documentDirectory`, so a 300 MB download of public
 *     artefacts rides along in every backup. `cacheDirectory`
 *     (Library/Caches) is the directory iOS already leaves out, and is where
 *     error reports and key exports are written.
 *   - The voting keys. The sentence further down about SecureStore holds on
 *     Android (EncryptedSharedPreferences is covered by the rules below); on
 *     iOS the Keychain IS included in an encrypted backup and restored onto a
 *     new device, because all 38 SecureStore calls in this tree pass no
 *     `keychainAccessible`, so none is `…ThisDeviceOnly`. That is audit item
 *     4b-M1a, still open.
 *
 * Why the iOS half is not implemented here rather than merely described:
 * `NSURLIsExcludedFromBackupKey` is a per-file attribute set at runtime on a
 * URL. It cannot be written from Info.plist, so a config plugin cannot set it;
 * it needs a native module plus a call at every directory this app creates,
 * and `ios/` is gitignored and regenerated, so nothing in this repository
 * could show that it worked. Deciding it, and 4b-M1a with it, is the product
 * owner's; leaving the header claiming a protection that does not exist was
 * not a decision at all.
 *
 * `android:allowBackup` defaults to `true` in the Expo template. Left on,
 * Android's Auto Backup copies the app's private storage — the AsyncStorage
 * database, `files/`, shared preferences — into the user's Google Drive, where
 * it is out of the phone's hands and restored onto a new device automatically.
 *
 * `android.allowBackup: false` in app.config.ts closes the cloud path. This
 * plugin adds the second half, which the Expo option does not cover: from
 * Android 12 (API 31) onwards, `allowBackup="false"` stops cloud backups but
 * leaves device-to-device transfer on, and this app targets API 36. So it
 * also writes res/xml/data_extraction_rules.xml, which excludes every domain
 * from BOTH `cloud-backup` and `device-transfer`, and points
 * `android:dataExtractionRules` at it.
 *
 * `android:fullBackupContent` is deliberately not set: it is the pre-Android
 * 12 mechanism, and on those versions `allowBackup="false"` already disables
 * backup entirely, with nothing left for a rule file to refine.
 *
 * What the Android user loses: nothing they can see while using the app, and
 * one thing when they change phone. Restoring a backup, or transferring to a
 * new device, no longer brings this app's data across; the app starts empty
 * and the document has to be scanned again. The voting keys were already
 * outside the Android backup (SecureStore = EncryptedSharedPreferences, which
 * Auto Backup does not carry), so this changes what a new phone inherits, not
 * what it can do. On iOS none of that applies: see the top of this file.
 *
 * android/ is gitignored and regenerated, so this has to be a plugin: a hand
 * edit to AndroidManifest.xml is wiped by the next `expo prebuild --clean`.
 */

const fs = require('node:fs');
const path = require('node:path');
const { withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');

const RULES_RESOURCE = 'data_extraction_rules';

/** Excluding the root domain of both transfer paths is the whole file. */
const DATA_EXTRACTION_RULES = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withNoBackup.js. Do not edit: android/ is regenerated. -->
<data-extraction-rules>
    <cloud-backup>
        <exclude domain="root" path="." />
        <exclude domain="file" path="." />
        <exclude domain="database" path="." />
        <exclude domain="sharedpref" path="." />
        <exclude domain="external" path="." />
    </cloud-backup>
    <device-transfer>
        <exclude domain="root" path="." />
        <exclude domain="file" path="." />
        <exclude domain="database" path="." />
        <exclude domain="sharedpref" path="." />
        <exclude domain="external" path="." />
    </device-transfer>
</data-extraction-rules>
`;

/** The manifest half, exported so a test can run it on a bare manifest. */
function applyNoBackup(application) {
  if (!application) throw new Error('[withNoBackup] AndroidManifest has no <application/> element');
  application.$ = application.$ || {};
  application.$['android:allowBackup'] = 'false';
  application.$['android:dataExtractionRules'] = `@xml/${RULES_RESOURCE}`;
  return application;
}

function withNoBackup(config) {
  const withManifest = withAndroidManifest(config, (cfg) => {
    applyNoBackup(cfg.modResults.manifest.application?.[0]);
    return cfg;
  });
  return withDangerousMod(withManifest, [
    'android',
    async (cfg) => {
      const dir = path.join(cfg.modRequest.platformProjectRoot, 'app', 'src', 'main', 'res', 'xml');
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, `${RULES_RESOURCE}.xml`), DATA_EXTRACTION_RULES, 'utf8');
      return cfg;
    },
  ]);
}

module.exports = withNoBackup;
module.exports.applyNoBackup = applyNoBackup;
module.exports.DATA_EXTRACTION_RULES = DATA_EXTRACTION_RULES;
module.exports.RULES_RESOURCE = RULES_RESOURCE;
