import { StyleSheet } from 'react-native';
import { Colors, Typography, Spacing } from '@/constants/theme';

export const modalStyles = StyleSheet.create({
  bottomSheetBackground: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: Spacing.modal.borderRadius,
    borderTopRightRadius: Spacing.modal.borderRadius,
  },
  handleIndicator: {
    backgroundColor: Colors.border,
    width: 40,
    height: 4,
  },
  container: {
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.background,
  },
  titleSection: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: Spacing.modal.titlePadding,
    paddingHorizontal: Spacing.modal.titlePaddingHorizontal,
    width: '100%',
    backgroundColor: Colors.white,
  },
  title: {
    flex: 1,
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.h1,
    color: Colors.primary,
    textAlign: 'center',
  },
  slidingWrapper: {
    overflow: 'hidden',
    alignSelf: 'stretch',
  },
  slidingContainer: {
    flexDirection: 'row',
  },
  stepSlide: {
    alignItems: 'center',
  },
  mediaContainer: {
    height: Spacing.modal.mediaContainerHeight,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.white,
    width: '100%',
  },
  contentSection: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    paddingVertical: Spacing.modal.contentPadding,
    paddingHorizontal: Spacing.modal.contentPaddingHorizontal,
    gap: Spacing.modal.contentGap,
    backgroundColor: Colors.background,
    width: '100%',
    height: Spacing.modal.contentSectionHeight,
  },
  stepContent: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: Spacing.modal.stepTitleGap,
    width: '100%',
  },
  stepHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.modal.stepTitleGap,
    width: '100%',
  },
  numberCircle: {
    width: Spacing.modal.numberCircleSize,
    height: Spacing.modal.numberCircleSize,
    borderRadius: Spacing.modal.numberCircleSize / 2,
    backgroundColor: Colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  numberText: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.bold,
    fontSize: Typography.fontSize.body,
    color: Colors.white,
  },
  stepTitle: {
    flex: 1,
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.settingRow,
    color: Colors.primary,
  },
  stepDescription: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.medium,
    fontSize: Typography.fontSize.body,
    lineHeight: Typography.lineHeight.body,
    letterSpacing: Typography.letterSpacing.settingRow,
    color: Colors.primary,
    width: '100%',
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: Spacing.modal.footerPadding,
    paddingHorizontal: Spacing.modal.footerPaddingHorizontal,
    gap: Spacing.modal.footerGap,
    backgroundColor: Colors.background,
    width: '100%',
  },
  progressContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.modal.progressBarGap,
  },
  progressBar: {
    flex: 1,
    height: Spacing.modal.progressBarHeight,
    borderRadius: Spacing.modal.progressBarRadius,
  },
  progressBarActive: {
    backgroundColor: Colors.progressActive,
  },
  progressBarInactive: {
    backgroundColor: Colors.progressInactive,
  },
  arrowButton: {
    width: Spacing.modal.arrowButtonSize,
    height: Spacing.modal.arrowButtonSize,
    borderRadius: Spacing.modal.arrowButtonRadius,
    backgroundColor: Colors.secondary,
    justifyContent: 'center',
    alignItems: 'center',
  },
});

export const stepSpecificStyles = StyleSheet.create({
  cardVideo: {
    width: Spacing.modal.cardImageWidth,
    height: Spacing.modal.cardImageHeight,
  },
  phoneImage: {
    width: Spacing.modal.phoneImageSize,
    height: Spacing.modal.phoneImageSize,
  },
  ballotImage: {
    width: Spacing.modal.ballotImageSize,
    height: Spacing.modal.ballotImageSize,
  },
  step4Container: {
    padding: Spacing.modal.step4Padding,
    gap: Spacing.modal.step4Gap,
    alignItems: 'center',
    width: '100%',
    backgroundColor: Colors.white,
  },
  step4Content: {
    gap: Spacing.modal.step4ContentGap,
    alignItems: 'flex-start',
    width: '100%',
  },
  step4Title: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.settingRow,
    color: Colors.primary,
    textAlign: 'center',
    width: '100%',
  },
  step4Description: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.medium,
    fontSize: Typography.fontSize.body,
    lineHeight: Typography.lineHeight.body,
    letterSpacing: Typography.letterSpacing.body,
    color: Colors.primary,
    width: '100%',
  },
  step4Video: {
    width: Spacing.modal.cardImageWidth,
    height: Spacing.modal.cardImageHeight,
  },
  step4Button: {
    paddingVertical: Spacing.modal.step4ButtonPaddingVertical,
    backgroundColor: Colors.secondary,
    alignItems: 'center',
    width: '100%',
  },
  step4ButtonText: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: Colors.white,
    textAlign: 'center',
  },
  step5Container: {
    paddingVertical: Spacing.modal.step5Padding,
    paddingHorizontal: 0,
    gap: Spacing.modal.step5Gap,
    alignItems: 'center',
    width: '100%',
    backgroundColor: Colors.white,
  },
  step5Title: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.settingRow,
    color: Colors.primary,
    textAlign: 'center',
    width: '100%',
  },
  step5Camera: {
    width: '100%',
    height: Spacing.modal.step5CameraHeight,
  },
  step5CameraOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  step5ScanArea: {
    width: '80%',
    height: 80,
    borderWidth: 2,
    borderColor: Colors.white,
    borderStyle: 'dashed',
    borderRadius: 8,
  },
  step5Button: {
    paddingVertical: Spacing.modal.step5ButtonPaddingVertical,
    backgroundColor: Colors.white,
    alignItems: 'center',
    width: '100%',
  },
  step5ButtonText: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: Colors.primary,
    textAlign: 'center',
  },
  step6Container: {
    paddingVertical: Spacing.modal.step6Padding,
    paddingHorizontal: 0,
    gap: Spacing.modal.step6Gap,
    alignItems: 'center',
    width: '100%',
    backgroundColor: Colors.white,
  },
  step6Title: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.settingRow,
    color: Colors.primary,
    textAlign: 'center',
    width: '100%',
  },
  step6ImageContainer: {
    width: '100%',
    alignItems: 'center',
  },
  step6Image: {
    width: Spacing.modal.step6ImageWidth,
    height: Spacing.modal.step6ImageHeight,
    backgroundColor: Colors.white,
  },
  step6ButtonContainer: {
    paddingHorizontal: Spacing.modal.step6ButtonPaddingHorizontal,
    width: '100%',
  },
  step6Button: {
    paddingVertical: Spacing.modal.step6ButtonPaddingVertical,
    backgroundColor: Colors.secondary,
    alignItems: 'center',
    width: '100%',
  },
  step6ButtonText: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: Colors.white,
    textAlign: 'center',
  },
  step7Container: {
    padding: Spacing.modal.step7Padding,
    gap: Spacing.modal.step7Gap,
    alignItems: 'center',
    width: '100%',
    backgroundColor: Colors.white,
  },
  step7Title: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.settingRow,
    color: Colors.primary,
    textAlign: 'center',
    width: '100%',
  },
  step7Image: {
    width: Spacing.modal.step7ImageSize,
    height: Spacing.modal.step7ImageSize,
  },
  step7Description: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.medium,
    fontSize: Typography.fontSize.body,
    lineHeight: Typography.lineHeight.body,
    letterSpacing: Typography.letterSpacing.body,
    color: Colors.primary,
    textAlign: 'center',
    width: '100%',
  },
  step8Container: {
    padding: Spacing.modal.step8Padding,
    gap: Spacing.modal.step8Gap,
    alignItems: 'center',
    width: '100%',
    backgroundColor: Colors.white,
  },
  step8Content: {
    gap: Spacing.modal.step8ContentGap,
    alignItems: 'center',
    width: '100%',
  },
  step8Title: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.h1,
    color: Colors.primary,
    textAlign: 'center',
    width: '100%',
  },
  step8SuccessAnimation: {
    width: Spacing.modal.step8SuccessSize,
    height: Spacing.modal.step8SuccessSize,
  },
  step8Button: {
    paddingVertical: Spacing.modal.step8ButtonPaddingVertical,
    backgroundColor: Colors.secondary,
    alignItems: 'center',
    width: '100%',
  },
  step8ButtonText: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: Colors.white,
    textAlign: 'center',
  },
  step9ErrorContainer: {
    padding: Spacing.modal.step9ErrorPadding,
    gap: Spacing.modal.step9ErrorGap,
    alignItems: 'center',
    width: '100%',
    backgroundColor: Colors.white,
  },
  step9ErrorContent: {
    gap: Spacing.modal.step9ErrorContentGap,
    alignItems: 'center',
    width: '100%',
  },
  step9ErrorTitle: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.h1,
    color: Colors.primary,
    textAlign: 'center',
    width: '100%',
  },
  step9ErrorDescription: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.medium,
    fontSize: Typography.fontSize.body,
    lineHeight: Typography.lineHeight.body,
    letterSpacing: Typography.letterSpacing.h1,
    color: Colors.primary,
    textAlign: 'center',
    width: '100%',
  },
  step9ErrorAnimation: {
    width: Spacing.modal.step9ErrorAnimationSize,
    height: Spacing.modal.step9ErrorAnimationSize,
  },
  step9ErrorButton: {
    paddingVertical: Spacing.modal.step9ErrorButtonPaddingVertical,
    backgroundColor: Colors.secondary,
    alignItems: 'center',
    width: '100%',
  },
  step9ErrorButtonText: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: Colors.white,
    textAlign: 'center',
  },
  step10Container: {
    padding: Spacing.modal.step10Padding,
    gap: Spacing.modal.step10Gap,
    alignItems: 'center',
    width: '100%',
    backgroundColor: Colors.white,
  },
  step10Content: {
    gap: Spacing.modal.step10ContentGap,
    alignItems: 'center',
    width: '100%',
  },
  step10Title: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.h1,
    color: Colors.primary,
    textAlign: 'center',
    width: '100%',
  },
  step10BallotVideo: {
    width: Spacing.modal.step10BallotSize,
    height: Spacing.modal.step10BallotSize,
  },
  step10ButtonContainer: {
    flexDirection: 'row',
    gap: Spacing.modal.step10ButtonGap,
    width: '100%',
  },
  step10CancelButton: {
    flex: 1,
    paddingVertical: Spacing.modal.step10ButtonPaddingVertical,
    backgroundColor: Colors.white,
    alignItems: 'center',
  },
  step10CancelButtonText: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: Colors.primary,
    textAlign: 'center',
  },
  step10ConfirmButton: {
    flex: 1,
    paddingVertical: Spacing.modal.step10ButtonPaddingVertical,
    backgroundColor: Colors.secondary,
    alignItems: 'center',
  },
  step10ConfirmButtonText: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: Colors.white,
    textAlign: 'center',
  },
  step11Container: {
    flex: 1,
    padding: Spacing.modal.step11Padding,
    gap: Spacing.modal.step11Gap,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    backgroundColor: Colors.white,
  },
  step11Loading: {
    width: Spacing.modal.step11LoadingWidth,
    height: Spacing.modal.step11LoadingHeight,
  },
  step12SuccessContainer: {
    padding: Spacing.modal.step12SuccessPadding,
    gap: Spacing.modal.step12SuccessGap,
    alignItems: 'center',
    width: '100%',
    backgroundColor: Colors.white,
  },
  step12SuccessContent: {
    gap: Spacing.modal.step12SuccessContentGap,
    alignItems: 'center',
    width: '100%',
  },
  step12SuccessTitle: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.h1,
    color: Colors.primary,
    textAlign: 'center',
    width: '100%',
  },
  step12SuccessDescription: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.medium,
    fontSize: Typography.fontSize.body,
    lineHeight: Typography.lineHeight.body,
    letterSpacing: Typography.letterSpacing.h1,
    color: Colors.primary,
    textAlign: 'center',
    width: '100%',
  },
  step12SuccessAnimation: {
    width: Spacing.modal.step12SuccessAnimationSize,
    height: Spacing.modal.step12SuccessAnimationSize,
  },
  step12SuccessButton: {
    paddingVertical: Spacing.modal.step12SuccessButtonPaddingVertical,
    backgroundColor: Colors.secondary,
    alignItems: 'center',
    width: '100%',
  },
  step12SuccessButtonText: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: Colors.white,
    textAlign: 'center',
  },
  step12ErrorContainer: {
    padding: Spacing.modal.step12ErrorPadding,
    gap: Spacing.modal.step12ErrorGap,
    alignItems: 'center',
    width: '100%',
    backgroundColor: Colors.white,
  },
  step12ErrorContent: {
    gap: Spacing.modal.step12ErrorContentGap,
    alignItems: 'center',
    width: '100%',
  },
  step12ErrorTitle: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.h1,
    color: Colors.primary,
    textAlign: 'center',
    width: '100%',
  },
  step12ErrorDescription: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.medium,
    fontSize: Typography.fontSize.body,
    lineHeight: Typography.lineHeight.body,
    letterSpacing: Typography.letterSpacing.h1,
    color: Colors.primary,
    textAlign: 'center',
    width: '100%',
  },
  step12ErrorAnimation: {
    width: Spacing.modal.step12ErrorAnimationSize,
    height: Spacing.modal.step12ErrorAnimationSize,
  },
  step12ErrorButton: {
    paddingVertical: Spacing.modal.step12ErrorButtonPaddingVertical,
    backgroundColor: Colors.secondary,
    alignItems: 'center',
    width: '100%',
  },
  step12ErrorButtonText: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: Colors.white,
    textAlign: 'center',
  },
});