import { StyleSheet } from 'react-native';
import { Colors, Typography, Spacing } from '@/constants/theme';

export const modalStyles = StyleSheet.create({
  bottomSheetBackground: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: Spacing.modal.borderRadius,
    borderTopRightRadius: Spacing.modal.borderRadius,
  },
  handleIndicator: {
    backgroundColor: Colors.border,
    width: 40,
    height: 4,
  },
  container: {
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.background,
  },
  titleSection: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: Spacing.modal.titlePadding,
    paddingHorizontal: Spacing.modal.titlePaddingHorizontal,
    width: '100%',
    backgroundColor: Colors.white,
  },
  title: {
    flex: 1,
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.h1,
    color: Colors.primary,
    textAlign: 'center',
  },
  slidingWrapper: {
    overflow: 'hidden',
    alignSelf: 'stretch',
  },
  slidingContainer: {
    flexDirection: 'row',
  },
  stepSlide: {
    alignItems: 'center',
  },
  mediaContainer: {
    height: Spacing.modal.mediaContainerHeight,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.white,
    width: '100%',
  },
  contentSection: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    paddingVertical: Spacing.modal.contentPadding,
    paddingHorizontal: Spacing.modal.contentPaddingHorizontal,
    gap: Spacing.modal.contentGap,
    backgroundColor: Colors.background,
    width: '100%',
    height: Spacing.modal.contentSectionHeight,
  },
  stepContent: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: Spacing.modal.stepTitleGap,
    width: '100%',
  },
  stepHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.modal.stepTitleGap,
    width: '100%',
  },
  numberCircle: {
    width: Spacing.modal.numberCircleSize,
    height: Spacing.modal.numberCircleSize,
    borderRadius: Spacing.modal.numberCircleSize / 2,
    backgroundColor: Colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  numberText: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.bold,
    fontSize: Typography.fontSize.body,
    color: Colors.white,
  },
  stepTitle: {
    flex: 1,
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.settingRow,
    color: Colors.primary,
  },
  stepDescription: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.medium,
    fontSize: Typography.fontSize.body,
    lineHeight: Typography.lineHeight.body,
    letterSpacing: Typography.letterSpacing.settingRow,
    color: Colors.primary,
    width: '100%',
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: Spacing.modal.footerPadding,
    paddingHorizontal: Spacing.modal.footerPaddingHorizontal,
    gap: Spacing.modal.footerGap,
    backgroundColor: Colors.background,
    width: '100%',
  },
  progressContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.modal.progressBarGap,
  },
  progressBar: {
    flex: 1,
    height: Spacing.modal.progressBarHeight,
    borderRadius: Spacing.modal.progressBarRadius,
  },
  progressBarActive: {
    backgroundColor: Colors.progressActive,
  },
  progressBarInactive: {
    backgroundColor: Colors.progressInactive,
  },
  arrowButton: {
    width: Spacing.modal.arrowButtonSize,
    height: Spacing.modal.arrowButtonSize,
    borderRadius: Spacing.modal.arrowButtonRadius,
    backgroundColor: Colors.secondary,
    justifyContent: 'center',
    alignItems: 'center',
  },
});

export const stepSpecificStyles = StyleSheet.create({
  cardVideo: {
    width: Spacing.modal.cardImageWidth,
    height: Spacing.modal.cardImageHeight,
  },
  phoneImage: {
    width: Spacing.modal.phoneImageSize,
    height: Spacing.modal.phoneImageSize,
  },
  ballotImage: {
    width: Spacing.modal.ballotImageSize,
    height: Spacing.modal.ballotImageSize,
  },
  step4Container: {
    padding: Spacing.modal.step4Padding,
    gap: Spacing.modal.step4Gap,
    alignItems: 'center',
    width: '100%',
    backgroundColor: Colors.white,
  },
  step4Content: {
    gap: Spacing.modal.step4ContentGap,
    alignItems: 'flex-start',
    width: '100%',
  },
  step4Title: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.settingRow,
    color: Colors.primary,
    textAlign: 'center',
    width: '100%',
  },
  step4Description: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.medium,
    fontSize: Typography.fontSize.body,
    lineHeight: Typography.lineHeight.body,
    letterSpacing: Typography.letterSpacing.body,
    color: Colors.primary,
    width: '100%',
  },
  step4Video: {
    width: Spacing.modal.cardImageWidth,
    height: Spacing.modal.cardImageHeight,
  },
  step4Button: {
    paddingVertical: Spacing.modal.step4ButtonPaddingVertical,
    backgroundColor: Colors.secondary,
    alignItems: 'center',
    width: '100%',
  },
  step4ButtonText: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: Colors.white,
    textAlign: 'center',
  },
});